Initial dockerfile build for ubuntu 16
Cisco-Security-Trust-Ops/debbuilder-dockerfile pull request #1
Opened 2018-04-11 19:23 UTC by jwstric2

Very similar to the rpmbuilder-dockerfile.  Allows for development and regression.  The user can mount his workspace in container and sudoers available.

```
$ winpty docker run -u `id -u`:`id -g` -it -v "C:\Users\jonatstr\debbuilder-dockerfile:/debbuilder"  jonatstr_ubuntu16 //bin//bash
GPG_KEY not defined; not setting state for signing debian packages
debbuilder@f5665cd14fc0:~$ sudo ls -al /root
total 16
drwx------ 2 root root 4096 Feb 28 19:14 .
drwxr-xr-x 1 root root 4096 Apr 11 19:31 ..
-rw-r--r-- 1 root root 3106 Oct 22  2015 .bashrc
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
debbuilder@f5665cd14fc0:~$ id
uid=1817657(debbuilder) gid=1049089(debbuilder) groups=1049089(debbuilder)
debbuilder@f5665cd14fc0:~$ ls
README.md  ubuntu16
debbuilder@f5665cd14fc0:~$
```

2018-04-11 19:34 UTC, wmborelli approved these changes

2018-04-11 20:04 UTC, pmfarnsw requested changes

2018-04-11 20:04 UTC, pmfarnsw commented on README.md
> +1. Allow sudoers access for testing install in container - NSS Wrapper does not play nicely with sudo due to LD_PRELOAD and other environment variables needed by NSS Wrapper to properly work.  The su
Even though it increments the second number should be 2. incase it's read in raw format.

2018-04-12 13:30 UTC, pmfarnsw approved these changes

2018-04-12 13:31 UTC, merged